# Generated by Django 5.0.6 on 2025-10-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_course_course_includes_course_preview_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_old', to='admin_part.course'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('total_lectures', models.PositiveIntegerField(default=0)),
                ('total_duration', models.CharField(blank=True, help_text='Example: 19min or 2h 15min', max_length=300, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='admin_part.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('duration', models.CharField(blank=True, help_text='Example: 05:05 or 10min', max_length=500, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='lectures/videos/')),
                ('is_preview', models.BooleanField(default=False)),
                ('resource', models.FileField(blank=True, null=True, upload_to='lectures/resources/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='admin_part.coursesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
