# Generated by Django 5.0.6 on 2025-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0004_remove_instructor_user_instructor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='social_links',
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
