# Generated by Django 5.2.7 on 2025-10-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_remove_instructor_social_links_instructor_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
