# Generated by Django 5.2.7 on 2025-10-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_remove_course_instructor_remove_lesson_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
