# Generated by Django 5.2.7 on 2025-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0007_remove_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='live_sessions/thumbnails/')),
                ('zoom_meeting_url', models.URLField()),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
