# Generated by Django 5.2.7 on 2025-10-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0008_livesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livesession',
            old_name='zoom_meeting_url',
            new_name='meeting_url',
        ),
    ]
