# Generated by Django 5.2.7 on 2025-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
