# Generated by Django 5.2.7 on 2025-10-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0011_remove_course_discount_remove_course_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='preview_video',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
