# Generated by Django 5.2.7 on 2025-10-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0012_remove_category_preview_video_delete_enrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Bundle',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='Bundle',
        ),
    ]
