# Generated by Django 5.2.7 on 2025-10-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0013_rename_category_bundle_rename_category_course_bundle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Bundle',
            new_name='bundle',
        ),
    ]
