# Generated by Django 5.0.6 on 2025-11-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0015_enrollment_refund_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
