# Generated by Django 5.2.7 on 2025-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0017_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='meeting_url',
        ),
        migrations.AddField(
            model_name='livesession',
            name='meeting_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
