# Generated by Django 5.0.6 on 2025-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0018_remove_livesession_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
