# Generated by Django 5.2.7 on 2025-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0018_remove_livesession_meeting_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration_seconds',
            field=models.FloatField(default=0, help_text='Total course duration in seconds'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lectures_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration_display',
            field=models.CharField(blank=True, help_text='Formatted duration', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='total_duration',
            field=models.FloatField(default=0, help_text='Total duration in seconds'),
        ),
    ]
