# Generated by Django 5.2.7 on 2025-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0019_remove_lecture_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lectures_count',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='duration_display',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 05:05 or 10min', max_length=500, null=True),
        ),
    ]
