# Generated by Django 5.0.6 on 2025-11-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0019_livesession_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='meeting_url',
        ),
    ]
