# Generated by Django 5.0.6 on 2025-11-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0020_remove_livesession_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
