# Generated by Django 5.2.7 on 2025-11-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0020_remove_course_total_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
