# Generated by Django 5.0.6 on 2025-11-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0021_livesession_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
