# Generated by Django 5.2.7 on 2025-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0021_alter_lecture_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='progress_percentage',
            field=models.FloatField(default=0, help_text='Percentage watched (0-100)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='total_duration',
            field=models.FloatField(default=0, help_text='Total video duration in seconds'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='watched_duration',
            field=models.FloatField(default=0, help_text='Total seconds watched'),
        ),
    ]
