# Generated by Django 5.0.6 on 2025-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0023_livesession_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='meeting_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
