# Generated by Django 5.2.7 on 2025-11-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0023_userstats'),
        ('admin_part', '0024_alter_livesession_meeting_number'),
    ]

    operations = [
    ]
