# Generated by Django 5.0.6 on 2025-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0025_merge_20251112_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='section_thumbnails/'),
        ),
    ]
