# Generated by Django 5.0.6 on 2025-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0026_coursesection_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='lecture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='section_thumbnails/'),
        ),
    ]
