# Generated by Django 5.2.7 on 2025-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0028_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video',
        ),
        migrations.AddField(
            model_name='lecture',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/originals/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/processed/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
