# Generated by Django 5.2.7 on 2025-12-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0029_remove_lecture_video_lecture_original_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='original_video',
            new_name='original_video_file',
        ),
        migrations.AddField(
            model_name='lecture',
            name='original_video_key',
            field=models.CharField(blank=True, help_text='S3 key of original uploaded video', max_length=500, null=True),
        ),
    ]
