# Generated by Django 5.2.7 on 2026-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0030_rename_original_video_lecture_original_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
