# Generated by Django 5.2.7 on 2026-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0031_alter_bundle_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
