# Generated by Django 5.2.7 on 2026-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0032_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='bundle_videos/'),
        ),
    ]
