# Generated by Django 5.2.7 on 2026-02-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0034_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bundle_pdfs/'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='bundle_pdf_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
