# Generated by Django 5.2.7 on 2026-02-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0035_bundle_bundle_pdf_bundle_bundle_pdf_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='purchase_type',
            field=models.CharField(choices=[('bundle', 'Bundle/Course Only'), ('pdf', 'PDF Only'), ('both', 'Bundle + PDF')], default='bundle', max_length=20),
        ),
    ]
