# Generated by Django 5.2.7 on 2026-02-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0036_alter_enrollment_unique_together_enrollment_has_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('meeting', 'Meeting (Everyone sees attendees)'), ('webinar', 'Webinar (Only host sees attendees)')], default='webinar', max_length=20),
        ),
    ]
