# Generated by Django 5.2.7 on 2026-02-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0037_livesession_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='session_type',
        ),
    ]
