# Generated by Django 5.2.7 on 2026-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0038_remove_livesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('webinar', 'Webinar (Privacy - Only host sees attendees)'), ('meeting', 'Meeting (Everyone sees attendees)')], default='webinar', max_length=20),
        ),
    ]
