# Generated by Django 5.2.7 on 2026-02-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0039_livesession_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview_video',
        ),
    ]
