# Generated by Django 5.0.6 on 2025-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdocipher_video_id', models.CharField(blank=True, help_text='VdoCipher videoId for DRM playback', max_length=128, null=True)),
            ],
        ),
    ]
