# Generated by Django 5.0.6 on 2025-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
